apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: cro-simple-tap-demo
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    app.kubernetes.io/part-of: cro-simple-tap-demo
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "11"
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: ssh://git@github.com/colrich/simple-java-app.git
      ref:
        branch: main
